In [29]:
import pandas as pd

#We create a dataframe

In [27]:

#Creating the dataframe
names = ["Chapman, Matt", "Olson, Matt", "Davis, Khris"]
positions = ["3B", "1B", "OF"]
hrs = [25,30,45]
df_plyrs = pd.DataFrame({"names":names, "pos":positions, "hr":hrs})
df_plyrs

           names pos  hr
0  Chapman, Matt  3B  25
1    Olson, Matt  1B  30
2   Davis, Khris  OF  45

#We use apply function to add a column for each players last name.

In [30]:
#Write your code here

def Get_lastN(column):
    name = column.split(" ")
    
    for i in range(len(name)):
        if "," in name[i]:
            return name[i]
    return column

df_plyrs["LastN"] = df_plyrs["names"].apply(Get_lastN)
df_plyrs

           names pos  hr     LastN
0  Chapman, Matt  3B  25  Chapman,
1    Olson, Matt  1B  30    Olson,
2   Davis, Khris  OF  45    Davis,

#We add a column showing if the player is an all-star category. We say a player is an all-star if they play in a third base position or outfield. Our threshold_hr = 20 homeruns. If the player is an all-star, then the row in the new column should become "all-star" otherwise it must be "not selected".

In [31]:
def allstart(df):
    position = df['pos']
    threshold_hr = df["hr"]
    if position == "3B" and threshold_hr>=20:
        return 'Yes'
    else:
        return 'No'
    
df_plyrs["All Star"] = df_plyrs.apply(allstart, axis=1)
df_plyrs

           names pos  hr     LastN All Star
0  Chapman, Matt  3B  25  Chapman,      Yes
1    Olson, Matt  1B  30    Olson,       No
2   Davis, Khris  OF  45    Davis,       No

In [18]:
df_plyrs.head()

           names pos  hr     LastN All Star
0  Chapman, Matt  3B  25  Chapman,      Yes
1    Olson, Matt  1B  30    Olson,       No
2   Davis, Khris  OF  45    Davis,       No

In [19]:
df = pd.read_csv("Movie_Reviews-3 2.tsv", sep='\t')
df.head()

,PhraseId,SentenceId,Phrase,Sentiment
0,1,1,A series of escapades demonstrating the adage ...,1
1,2,1,A series of escapades demonstrating the adage ...,2
2,3,1,A series,2
3,4,1,A,2
4,5,1,series,2

In [20]:
def Sentiment(df):
    
    sentiment = df['Sentiment']
    if sentiment == 0:
        return 'Negative'
    elif sentiment == 1:
        return 'Somewhat Negative' 
    elif sentiment == 2:
        return 'Neutral' 
    elif sentiment == 3:
        return 'Somewhat Positive' 
    else:
        return 'Positive' 
    
df['Sentiment_Meanings'] = df.apply(Sentiment,axis=1)
df

,PhraseId,SentenceId,Phrase,Sentiment,Sentiment_Meanings
0,1,1,A series of escapades demonstrating the adage ...,1,Somewhat Negative
1,2,1,A series of escapades demonstrating the adage ...,2,Neutral
2,3,1,A series,2,Neutral
3,4,1,A,2,Neutral
4,5,1,series,2,Neutral
...,...,...,...,...,...
156055,156056,8544,Hearst 's,2,Neutral
156056,156057,8544,forced avuncular chortles,1,Somewhat Negative
156057,156058,8544,avuncular chortles,3,Somewhat Positive
156058,156059,8544,avuncular,2,Neutral
156059,156060,8544,chortles,2,Neutral

#we get rid of all phrases that have fewer than 10 words

In [32]:
#Add phrase_length column

def count_phrase(df):
    phrase = df['Phrase']
    
    words = phrase.split(" ")
    
    return len(words)

df['Phrase Count'] = df.apply(count_phrase, axis=1)

In [26]:
df.tail()

,PhraseId,SentenceId,Phrase,Sentiment,Sentiment_Meanings,Phrase Count
156041,156042,8544,"is darkly atmospheric , with Herrmann quietly ...",2,Neutral,18
156044,156045,8544,with Herrmann quietly suggesting the sadness a...,2,Neutral,14
156045,156046,8544,Herrmann quietly suggesting the sadness and ob...,2,Neutral,13
156047,156048,8544,quietly suggesting the sadness and obsession b...,1,Somewhat Negative,12
156048,156049,8544,suggesting the sadness and obsession beneath H...,2,Neutral,11

In [24]:
#Get ride of phrases that have fewer than 10 words
def get_rid_10(df):
    df.drop(df[df['Phrase Count'] < 10].index, inplace = True)

get_rid_10(df)
df

,PhraseId,SentenceId,Phrase,Sentiment,Sentiment_Meanings,Phrase Count
0,1,1,A series of escapades demonstrating the adage ...,1,Somewhat Negative,37
1,2,1,A series of escapades demonstrating the adage ...,2,Neutral,14
5,6,1,of escapades demonstrating the adage that what...,2,Neutral,12
7,8,1,escapades demonstrating the adage that what is...,2,Neutral,11
9,10,1,demonstrating the adage that what is good for ...,2,Neutral,10
...,...,...,...,...,...,...
156041,156042,8544,"is darkly atmospheric , with Herrmann quietly ...",2,Neutral,18
156044,156045,8544,with Herrmann quietly suggesting the sadness a...,2,Neutral,14
156045,156046,8544,Herrmann quietly suggesting the sadness and ob...,2,Neutral,13
156047,156048,8544,quietly suggesting the sadness and obsession b...,1,Somewhat Negative,12
156048,156049,8544,suggesting the sadness and obsession beneath H...,2,Neutral,11

#We got rid of phrases with less 10 words